# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/robosar/robosar_gui/src/robosar_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

import os
from PyQt5 import QtCore, QtGui, QtWidgets

ROOT_DIR = os.path.realpath(os.path.join(os.path.dirname(__file__), '..', 'img'))


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1027, 834)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Dialog.setPalette(palette)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(200, 100))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(os.path.join(ROOT_DIR, "robosar_logo_big.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(10000, 50))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMaximumSize(QtCore.QSize(200, 100))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.active_agents_label = QtWidgets.QLabel(self.groupBox_4)
        self.active_agents_label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.active_agents_label.setFont(font)
        self.active_agents_label.setAlignment(QtCore.Qt.AlignCenter)
        self.active_agents_label.setObjectName("active_agents_label")
        self.horizontalLayout_5.addWidget(self.active_agents_label)
        self.verticalLayout_11.addWidget(self.groupBox_4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setMinimumSize(QtCore.QSize(50, 50))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.area_explored_label = QtWidgets.QLabel(self.groupBox_5)
        self.area_explored_label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.area_explored_label.setFont(font)
        self.area_explored_label.setAlignment(QtCore.Qt.AlignCenter)
        self.area_explored_label.setObjectName("area_explored_label")
        self.horizontalLayout_6.addWidget(self.area_explored_label)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.victims_found_label = QtWidgets.QLabel(self.groupBox_6)
        self.victims_found_label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.victims_found_label.setFont(font)
        self.victims_found_label.setAlignment(QtCore.Qt.AlignCenter)
        self.victims_found_label.setObjectName("victims_found_label")
        self.horizontalLayout_7.addWidget(self.victims_found_label)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.life_score_label = QtWidgets.QLabel(self.groupBox_7)
        self.life_score_label.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.life_score_label.setFont(font)
        self.life_score_label.setAlignment(QtCore.Qt.AlignCenter)
        self.life_score_label.setObjectName("life_score_label")
        self.horizontalLayout_8.addWidget(self.life_score_label)
        self.verticalLayout_12.addWidget(self.groupBox_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(320, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777213, 16777215))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(320, 500))
        self.scrollArea.setMaximumSize(QtCore.QSize(400, 10000))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(2, 0, 300, 498))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(300, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_9.addWidget(self.scrollArea)
        self.verticalLayout_6.addWidget(self.groupBox_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.task_image = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_image.sizePolicy().hasHeightForWidth())
        self.task_image.setSizePolicy(sizePolicy)
        self.task_image.setMinimumSize(QtCore.QSize(400, 200))
        self.task_image.setText("")
        self.task_image.setScaledContents(False)
        self.task_image.setAlignment(QtCore.Qt.AlignCenter)
        self.task_image.setObjectName("task_image")
        self.verticalLayout_8.addWidget(self.task_image)
        self.verticalLayout_7.addWidget(self.groupBox, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mission_timer_label = QtWidgets.QLabel(self.groupBox_3)
        self.mission_timer_label.setMaximumSize(QtCore.QSize(300, 1000))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.mission_timer_label.setFont(font)
        self.mission_timer_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mission_timer_label.setObjectName("mission_timer_label")
        self.verticalLayout_3.addWidget(self.mission_timer_label)
        self.start_timer_button = QtWidgets.QPushButton(self.groupBox_3)
        self.start_timer_button.setObjectName("start_timer_button")
        self.verticalLayout_3.addWidget(self.start_timer_button)
        self.stop_timer_button = QtWidgets.QPushButton(self.groupBox_3)
        self.stop_timer_button.setObjectName("stop_timer_button")
        self.verticalLayout_3.addWidget(self.stop_timer_button)
        self.restart_timer_button = QtWidgets.QPushButton(self.groupBox_3)
        self.restart_timer_button.setObjectName("restart_timer_button")
        self.verticalLayout_3.addWidget(self.restart_timer_button)
        self.verticalLayout_5.addWidget(self.groupBox_3, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start_mission_button = QtWidgets.QPushButton(Dialog)
        self.start_mission_button.setMaximumSize(QtCore.QSize(200, 100))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(os.path.join(ROOT_DIR, "k4-detail1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_mission_button.setIcon(icon)
        self.start_mission_button.setIconSize(QtCore.QSize(25, 25))
        self.start_mission_button.setObjectName("start_mission_button")
        self.horizontalLayout_3.addWidget(self.start_mission_button)
        self.e_stop_button = QtWidgets.QPushButton(Dialog)
        self.e_stop_button.setMaximumSize(QtCore.QSize(200, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(os.path.join(ROOT_DIR, "stop_sign_button.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.e_stop_button.setIcon(icon1)
        self.e_stop_button.setIconSize(QtCore.QSize(25, 25))
        self.e_stop_button.setObjectName("e_stop_button")
        self.horizontalLayout_3.addWidget(self.e_stop_button)
        self.homing_button = QtWidgets.QPushButton(Dialog)
        self.homing_button.setMaximumSize(QtCore.QSize(200, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(os.path.join(ROOT_DIR, "avengers__endgame__2019__avengers_logo_png__by_mintmovi3_dd4bz30-fullview.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homing_button.setIcon(icon2)
        self.homing_button.setIconSize(QtCore.QSize(25, 25))
        self.homing_button.setObjectName("homing_button")
        self.horizontalLayout_3.addWidget(self.homing_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Mission Control"))
        self.groupBox_4.setTitle(_translate("Dialog", "Active Agents"))
        self.active_agents_label.setText(_translate("Dialog", "0"))
        self.groupBox_5.setTitle(_translate("Dialog", "% Area Explored"))
        self.area_explored_label.setText(_translate("Dialog", "0"))
        self.groupBox_6.setTitle(_translate("Dialog", "Victims Found"))
        self.victims_found_label.setText(_translate("Dialog", "0"))
        self.groupBox_7.setTitle(_translate("Dialog", "Sum of Time"))
        self.life_score_label.setText(_translate("Dialog", "0"))
        self.groupBox_2.setTitle(_translate("Dialog", "Agent Status"))
        self.groupBox.setTitle(_translate("Dialog", "Task Allocation"))
        self.groupBox_3.setTitle(_translate("Dialog", "Mission Timer"))
        self.mission_timer_label.setText(_translate("Dialog", "00:00"))
        self.start_timer_button.setText(_translate("Dialog", "Resume"))
        self.stop_timer_button.setText(_translate("Dialog", "Pause"))
        self.restart_timer_button.setText(_translate("Dialog", "Reset"))
        self.label_6.setText(_translate("Dialog", "Actions"))
        self.start_mission_button.setText(_translate("Dialog", "Start Mission"))
        self.e_stop_button.setText(_translate("Dialog", " E-Stop"))
        self.homing_button.setText(_translate("Dialog", "  Avengers Assemble"))
